services:
  # 1. USŁUGA BAZY DANYCH (POSTGRESQL)
  db:
    image: postgres:16
    container_name: beauty_db
    restart: unless-stopped
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. USŁUGA ZARZĄDZANIA BAZĄ DANYCH (PGADMIN)
  pgadmin:
    image: dpage/pgadmin4
    container_name: beauty_pgadmin
    restart: unless-stopped
    env_file: .env # Użyje PGADMIN_DEFAULT_EMAIL i PGADMIN_DEFAULT_PASSWORD
    ports:
      - "5050:5050"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      db:
        condition: service_healthy # Kluczowe, aby poczekać na gotowość DB

  # 3. USŁUGA BACKENDOWA (DJANGO REST FRAMEWORK)
  backend:
    build: ./beauty-salon-backend # Wskazanie na folder z Dockerfile dla Django
    container_name: beauty_backend
    restart: unless-stopped
    env_file: .env # Dostęp do zmiennych DB
    ports:
      - "8000:8000" # Wystawienie portu dla API
    depends_on:
      db:
        condition: service_healthy # Uruchom, gdy DB będzie w pełni gotowa
    volumes:
      - ./beauty-salon-backend:/app
    command: python manage.py runserver 0.0.0.0:8000 # Polecenie startowe

volumes:
  pgdata:
  pgadmin_data: # Wolumen dla trwałości danych PgAdmin